# Generated by Django 3.2.7 on 2021-12-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20211215_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='pincode',
            field=models.TextField(),
        ),
    ]
